export const cuisines = ref([
  { value: 'African', label: 'Африканская' },
  { value: 'American', label: 'Американская' },
  { value: 'British', label: 'Британская' },
  { value: 'Cajun', label: 'Каджунская' },
  { value: 'Caribbean', label: 'Карибская' },
  { value: 'Chinese', label: 'Китайская' },
  { value: 'Eastern European', label: 'Восточно-европейская' },
  { value: 'European', label: 'Европейская' },
  { value: 'French', label: 'Французская' },
  { value: 'German', label: 'Немецкая' },
  { value: 'Greek', label: 'Греческая' },
  { value: 'Indian', label: 'Индийская' },
  { value: 'Irish', label: 'Ирландская' },
  { value: 'Italian', label: 'Итальянская' },
  { value: 'Japanese', label: 'Японская' },
  { value: 'Jewish', label: 'Еврейская' },
  { value: 'Korean', label: 'Корейская' },
  { value: 'Latin American', label: 'Латиноамериканская' },
  { value: 'Mediterranean', label: 'Средиземноморская' },
  { value: 'Mexican', label: 'Мексиканская' },
  { value: 'Middle Eastern', label: 'Ближневосточная' },
  { value: 'Nordic', label: 'Северная' },
  { value: 'Southern', label: 'Южная' },
  { value: 'Spanish', label: 'Испанская' },
  { value: 'Thai', label: 'Тайская' },
  { value: 'Vietnamese', label: 'Вьетнамская' },
])

export const diets = ref([
  { value: 'Gluten Free', label: 'Без глютена' },
  { value: 'Ketogenic', label: 'Кетогенная' },
  { value: 'Vegetarian', label: 'Вегетарианская' },
  { value: 'Lacto-Vegetarian', label: 'Лакто-Вегетарианская' },
  { value: 'Ovo-Vegetarian', label: 'Ово-Вегетарианская' },
  { value: 'Vegan', label: 'Веганская' },
  { value: 'Pescetarian', label: 'Пескетарианская' },
  { value: 'Paleo', label: 'Палеодиета' },
  { value: 'Primal', label: 'Примитивная' },
  { value: 'Low FODMAP', label: 'Низкий FODMAP' },
  { value: 'Whole30', label: 'Whole30' },
])

export const types = ref([
  { value: 'main course', label: 'Основное блюдо' },
  { value: 'side dish', label: 'Гарнир' },
  { value: 'dessert', label: 'Десерт' },
  { value: 'appetizer', label: 'Закуска' },
  { value: 'salad', label: 'Салат' },
  { value: 'bread', label: 'Хлеб' },
  { value: 'breakfast', label: 'Завтрак' },
  { value: 'soup', label: 'Суп' },
  { value: 'beverage', label: 'Для питья' },
  { value: 'sauce', label: 'Соус' },
  { value: 'marinade', label: 'Маринад' },
  { value: 'fingerfood', label: 'Легкая закуска' },
  { value: 'snack', label: 'Перекус' },
  { value: 'drink', label: 'Напиток' },
])

export const intolerances = ref([
  { value: 'Dairy', label: 'Молочные продукты' },
  { value: 'Egg', label: 'Яйца' },
  { value: 'Gluten', label: 'Глютен' },
  { value: 'Grain', label: 'Зерновые' },
  { value: 'Peanut', label: 'Арахис' },
  { value: 'Seafood', label: 'Морепродукты' },
  { value: 'Sesame', label: 'Кунжут' },
  { value: 'Shellfish', label: 'Моллюски' },
  { value: 'Soy', label: 'Соя' },
  { value: 'Sulfite', label: 'Сульфиты' },
  { value: 'Tree Nut', label: 'Орехи' },
  { value: 'Wheat', label: 'Пшеница' },
])
